# Build settings
permalink   : /blog/:year/:title/
highlighter : rouge
paginate: 5
paginate_path: "/blog/page/:num/"
comments: true
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
sass:
  sass_dir: _scss
  style: compressed

# SEO settings
title: مهدی مشتاقی
description: "مهدی مشتاقی هستم، توسعه دهنده وب"
keywords: "مهدی مشتاقی, مشتاقی, طراحی وب، روزمره"
url: http://moshtaghi.ir
google_analytics: UA-9152888-2
repo: https://github.com/moshtaghi/moshtaghi.github.io/tree/source
disqus_shortname: "moshtaghi"
disqus_site_shortname: "moshtaghi"

# Author settings
author:
  name      : مهدی مشتاقی
  job       : توسعه دهنده FrondEnd
  bio       : "لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون"
  thumb     : /images/author.jpg
  email     : moshtaghi.m@gmail.com
  url       : http://moshtaghi.ir
  github    : https://github.com/moshtaghi
  twitter   : https://twitter.com/moshtaghi
  linkedin  : https://linkedin.com/in/moshtaghim
  telegram  : https://t.me/moshtaghim

# navbar pages
navbar:
  - slug: about
    title: درباره
  - slug: blog
    title: وبلاگ
exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]